- .travis.yml
- BUILD.bazel
- README.md
- dependencies.bzl
- spectator/sample_config.cc
`spectatord_main` had a direct dependency on an internal config package
used at Netflix. This is not accessible from outside the internal
network and therefore travis cannot successfully complete the build.
> Remove direct dependency on internal artifact

- .bazelrc
The memory sanitizer config option now successfully compiles the project but
unfortunately we cannot run our tests with it due to some gtest issues.
Apparently it requires we use libc++ and compile it under msan.
The tsan (thread sanitizer) and ubsan (undefined behavior sanitizer)
configs both work and are able to run our tests successfully and the
main program. A nice improvement would be to add them as steps to the
travis build
> Tweak the msan config

- .bazelrc
- .travis.yml
Trying to improve the performance of the travis builds. It's currently
taking around 9 and 11 minutes for clang and gcc respectively.
> Tweak travis build

- .travis.yml
For travis just focus on the clang build for now since the gcc is taking
a long time. We might re-enable it in the future if we find a more
performant way of executing multiple builds while caching the
dependencies
> Only compile using clang

- .travis.yml
- BUILD.bazel
In order to reduce dependencies on system libraries. This makes it
possible to compile on bionic and run on xenial.
> Statically link against libbfd

- BUILD.bazel
- README.md
- bin/test_main.cc
- server/spectatord.cc
- server/spectatord.h
- server/spectatord_test.cc
- spectator/id.cc
- spectator/id.h
- spectator/monotonic_counter_test.cc
- spectator/monotonic_sampled.cc
- spectator/monotonic_sampled.h
- spectator/monotonic_sampled_test.cc
- spectator/registry.cc
- spectator/registry.h
- spectator/registry_test.cc
- spectator/string_intern.h
- spectator/tags.h
Update the payload format by removing the protocol version and
introducing tags with a comma instead of `:#`
In order to help implement some sidecars that are relaying samples from
other sources, we add a new meter type which is a monotonic source that
was sampled at a given time in the recent past using the type `X`. This
is experimental and subject to be removed based on feedback.
`X,1000:some.name:1`
`X,2000:some.name:2`
> New payload fmt and add monotonically sampled ctrs

- bench/README.md
- bench/get_measurement_bench.cc
- bench/measurements_fmt_bench.cc
- spectator/http_client_test.cc
- spectator/log_entry.h
- spectator/perc_dist_summary_test.cc
- spectator/perc_timer_test.cc
- spectator/publisher.h
- spectator/registry.cc
- spectator/registry.h
- spectator/registry_test.cc
- spectator/sample_config.cc
Previously the way we were creating `Id`s was to use
`registry->CreateId(...)` with the idea of being able to have `Id`s that
were customized to a particular registry. This hasn't been needed at all
and it just makes things too verbose. Switch the creation to
`Id::Of(name, [tags])` instead.
> Remove registry specific Id creation

- bin/spectatord_main.cc
- server/spectatord.cc
- spectator/registry.cc
Do not run our statsd server unless the user explicitly asks for it.
> Disable statsd support by default

- server/proc_utils.cc
- server/spectatord.cc
We were not ensuring the correct termination of the string containing
a number when parsing the proc file `rmem_max`.
> Make sure to zero terminate proc strings

- server/spectatord.cc
- server/spectatord_test.cc
It was still expecting the version number which has been removed from
the docs. Now the behavior matches the documentation
> Fix parsing of messages

- bin/spectatord_main.cc
- spectator/config.h
- spectator/http_client.cc
- spectator/http_client.h
- spectator/publisher.h
- tools/metrics_gen.cc
Sometimes it can be useful when debugging certain scenarios. This
basically is just a wrapper to enable `CURLOPT_VERBOSE` sending the
output to `stdout`
> Add an option to trace http requests

- .travis.yml
- BUILD.bazel
- bin/spectatord_main.cc
- spectator/config.h
- spectator/http_client.cc
- spectator/http_client.h
- spectator/publisher.h
- spectator/version.h
- tools/generate_version.sh
It makes it easier to distinguish among HTTP requests, esp. when
originating from the same host.
In addition rename the `--trace` option to `--verbose_http`
> Update user-agent to include the spectatord ver

- spectator/counter.cc
- spectator/gauge.cc
- spectator/id.h
- spectator/tags.h
We were mistakingly comparing to the `end()` iterator for
found/not-found functionality in tags but since we switched
to a sorted array implementation we need to verify that
the iterator points to the actual key in addition to comparing
to the end.
> Fix tags has/at functionality

- README.md
This was how the feature was planned to be implemented but since it only
applies to `X` the timestamp follows the type, in a manner analog to how
the ttl follows the gauge.
> Remove reference to @timestamp

- spectator/monotonic_counter.cc
- spectator/monotonic_counter_test.cc
Previously we were ignoring the statistic tag provided by the user and
always using count. This change makes it consistent with the behavior of
regular counters.
> User specified statistic for monotonic counters

- BUILD.bazel
- server/spectatord.cc
- spectator/age_gauge.h
- spectator/age_gauge_test.cc
- spectator/http_client_test.cc
- spectator/log_entry.h
- spectator/monotonic_counter_test.cc
- spectator/registry.cc
- spectator/registry.h
- spectator/registry_test.cc
This adds an 'age gauge' metric that reports the number of seconds the
spectatord process has been running. This can be used to track restarts
due to various causes
> Report the uptime for the spectatord process

- server/spectatord.cc
- server/spectatord.h
- spectator/http_client_test.cc
- spectator/publisher.h
- spectator/registry.h
If for any reason we are not able to successfully send metrics in over 1
minute, abort the process. (Hopefully coredumps are enabled and we can
debug further)
> Periodically check we are actively working

- README.md
- server/spectatord.cc
- server/spectatord_test.cc
This will make it easy to use one of our recommended patterns for
alerting, a time since last success, which is usually a much better
approach than trying to alert on lack of errors.
> Add support for an Age gauge type

- bin/spectatord_main.cc
- bin/test_main.cc
We've seen this cause some issues in relation to tcmalloc, but just to
be extra safe. We do not attempt to print a stacktrace when we get an
ABRT signal.
> Do not trap SIGABRT

- spectator/tags.h
- spectator/tags_test.cc
We are using a small buffer optimization for tags where we do not need
to allocate memory if the number of tags is <= 8. We are saving memory
by reusing the array of tags to store the capacity when the tags live on
the heap. However we were not initializing the capacity correctly when
copying/moving from another large Tags value.
> Fix bug when copying large tag values

- .gitignore
- Dockerfile
- bin/spectatord_main.cc
- build.sh
- server/spectatord.cc
- server/spectatord.h
We have some teams that would prefer to run this service without the UNIX
domain socket. To preserve backward compatibility, the default value of this
flag is true.
The handling of enable flags has been adjusted slightly, so that optionals
are used, which makes the code a little easier to read when passing these
values around.
A few functions which are no longer needed since the switch to the Abseil
flags library have been removed.
A Dockerfile and build script have been added to the project, to provide a
reproducible means of running builds locally. To use this build script, you
must provide a BASEOS_IMAGE environment variable, which should resolve to a
reasonable image, such as an Ubuntu LTS version.
In order to allow the build to complete successfully, it is recommended to
configure …
> add --enable_socket flag to allow for disabling the unix socket

- spectator/registry.h
They're useful for tracking metrics that might not be updated
frequently.
> Do not expire age gauges

- BUILD.bazel
- bin/spectatord_main.cc
- server/spectatord_test.cc
- spectator/config.h
- spectator/config_test.cc
- spectator/registry.cc
- spectator/registry.h
- spectator/test_utils.h
As discussed in #23, this PR implements a limit on the maximum number of age gauges that may be reported from a `spectatord` process.
The purpose of this feature is to limit a potential source of memory leaks for long-running `spectatord` processes where the tags associated with an age gauge vary over time. The limit defaults to 1000 and we do not think that most users will hit this limit on a per-node basis. The limit is customizable with the `--age_gauge_limit` flag, in the event that users need to adjust this setting for their particular service.
> Age Gauge Limit Flag

- dependencies.bzl
This supports the addition of the age_gauge_limit flag.
> update netflix internal config dependency

- build.sh
- server/spectatord.cc
This bug was introduced with the PR that added the --enable_unix_socket
flag. The creation of the server was moved into the scope of an if
statement, which meant that it was not available to the io context
when it started, which produced the following errors:
[info] Starting local server (dgram) on socket /run/spectatord/spectatord.unix
[error] Error receiving: 125: Operation aborted.
[error] Error receiving: 9: Bad file descriptor
This change follows the model of the statsd server, by declaring a unique
pointer to the local server outside the scope of the if statement.
> fix local server startup

- bin/spectatord_main.cc
The original PR was submitted with --enable_socket in the title and the
change that landed was --enable_unix_socket. The shorter name is a bit
better, so this change brings that back to the original spec.
The flags have have been sorted into three broad categories: (1) flags
that affect the daemon interfaces, (2) flags that control the registry
behavior and (3) flags that control logging.
> adjust flag name for enabling the unix socket

- spectator/compressed_buffer.cc
- spectator/compressed_buffer.h
- spectator/compressed_buffer_test.cc
Before there was a bug when compress was called with
`Z_FINISH` if the destination buffer was not big enough.
It would only keep looping while `avail_in > 0`. However,
it needs to check for `Z_STREAM_END` to ensure that the
compressed buffer is actually finished.
> ensure compressed buffer is finished

- server/spectatord.cc
- spectator/publisher.h
If an instance had a disabled file defined, then spectatord would never
send metrics, which would cause it to abort every minute and fill up
available disk space with core files.
This change considers whether or not spectatord is enabled when checking the
last time since it was able to send metrics successfully.
Added a trace log for the condition where we skip sending metrics, to make
it more obvious what is happening when verbose logging is enabled.
> do not abort when disabled

- server/spectatord.cc
- spectator/http_client.cc
- spectator/http_client_test.cc
- spectator/publisher.h
There are a number of containers which are launched on Titus that do not
have a configuration which allows them to publish metrics. This leads to
two additional sources of noise in that environment:
* HTTP timeouts with three retries will be encountered every 5 seconds
and there will be a failed attempt to parse a non-existent error response.
* Since no metrics are sent, the daemon will abort every minute, leaving
behind core files, which will eventually fill up the disk.
This change removes the `ensure_not_stuck` watchdog from the main upkeep
loop, to prevent the aborts from occurring. We keep the function in the
code, so that we can rapidly re-enable it for snapshot builds, if we need
it for debugging.
For HTTP timeouts, we now set the `http_code` to a `-1` value, which matches
the …
> reduce titus error logging

- spectator/publisher.h
This provides confirmation that the ATLAS_SKIP_COMMON_TAGS feature is
taking effect.
> log common tags at startup

- dependencies.bzl
This update adds support for the nf.container and nf.process tags. However,
the values for these should be provided by local process contexts and thus
supplied by clients executing in those environments. To prevent these from
being added to all metrics sent by spectatord, a few environment variables
will need to be unset in the start script for spectatord.
> latest spectator-cppconf

- CMakeLists.txt
The addition of libbfd is intended to provide prettier stack traces with backwards-cpp. Linking against libbfd has never worked correctly for this project and it complicates the build, so remove it and stick with the basic stack tracing enabled by the header-only implementation of backwards.
Full static linking of the main binary results in segfaults, due to the use of libnss, so drop back to only static linking libstdc++, which is necessary for running on Titus.
> remove libbfd configuration

- .clang-format
- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- admin/CMakeLists.txt
- admin/admin_server.cc
- admin/admin_server.h
- admin/admin_server_test.cc
- bin/spectatord_main.cc
- build.sh
- conanfile.py
- requirements.txt
- server/spectatord.cc
- spectator/registry.cc
- spectator/registry.h
- spectator/registry_test.cc
- spectator/sample_config.cc
- spectator/string_intern_test.cc
- tools/admin-server-cli-test.sh
This change adds an administrative server to SpectatorD, for the purpose of providing debugging information and making small changes to the running configuration.
The Mantis application needed the ability to change their common tags on the fly during operation, as they swap out jobs and the `/config/common_tags` endpoint provides this feature.
Users of AgeGauges occasionally need the ability to delete the AgeGauges they create - the `/metrics/A` endpoint provides this feature.
> admin server

- CMakeLists.txt
- bin/spectatord_main.cc
- bin/test_main.cc
Linking against this library introduces strong distro-specific requirements which complicates the build and distribution process. We want to keep things simple and as generic as possible, so we will abandon getting ultimate stack traces on the Linux platform.
To help deal with segmentation faults, we will press forward with migrating to systemd startup scripts, so that we can control the behavior of core dumps.
> revert libbfd linking for backward-cpp

- spectator/publisher.h
The `Sent:` messages serve as a positive confirmation that spectatord is either delivering or dropping measurements, but there is generally no action to be taken from it directly, and this information is also recorded in the `spectator.measurements` metric.
In the case of Titus, this message alone is responsible for 25% of all logs.
Moving this message to the `debug` level drops it from the standard use case, while still allowing it to be accessed if the `--verbose` flag is passed to the binary.
Fixes #71.
> reduce spectatord logging

- docs/METRICS.md
- spectator/publisher.h
- spectator/registry.cc
- spectator/registry_test.cc
This allows these metrics to be tracked back to spectatord, as needed, and it mirrors the tagging convention for ipc metrics.
> add owner tag to generic spectator metrics

- .gitignore
- README.md
- build.sh
The clean function of the build script was removing the conan binary cache far too often, resulting in slower builds. This should be a special action that is only done when switching between Debug and Release builds, where there is an impact on the use of the address sanitizer.
> update build script

- spectator/publisher.h
The logging was reduced for the common standard operating case, but it should also consider the case when there are errors.
> always log publisher status when num_err > 0

- README.md
- server/spectatord.cc
- spectator/measurement.h
- spectator/monotonic_sampled.cc
- spectator/monotonic_sampled.h
These values are not expected to rollover and will not ever go as high as the actual data values.
> monotonic sampled counter nanos should remain int64_t

- bin/spectatord_main.cc
- server/spectatord.cc
- spectator/config.h
- spectator/http_client.cc
- spectator/http_client.h
- spectator/http_client_test.cc
- spectator/log_entry.h
- spectator/publisher.h
The purpose of this flag is to remove all common tags, so that users can override any common tags they wish, including `nf.app`, by providing them in the protocol line. Note that a proper environment is still required, so that the publish URI can be determined correctly.
This feature should only be used for secondary spectatord processes on an instance. A standard process should exist, so that atlas-system-agent metrics can be received and published.
When this feature is active, the publishing of internal status metrics is disabled, because we cannot attribute the metrics correctly in the absence of common tags.
> add --no_common_tags flag

- .github/workflows/build.yml
- spectator/config.h
- spectator/config_test.cc
We are not ready to use this value just yet, but this change keeps the config definition synchronized so that we can use the latest version.
Update GitHub actions to the latest version, to squelch warnings.
> add external uri field to config

- spectator/registry.cc
This change is related to the work in the previous PR:                                                                                                                                                  
https://github.com/Netflix-Skunkworks/spectatord/pull/89
> check status_metrics_enabled before publishing registrySize metrics

- conanfile.py
This contains a fix to ensure that the config is always a unique_ptr.
> latest config

- spectator/monotonic_counter_uint.cc
- spectator/monotonic_counter_uint_test.cc
> report zero values for unexpected overflows in MonotonicCounterUint

- bench/parse_bench.cc
- bench/statsd_bench.cc
- bin/spectatord_main.cc
- server/spectatord.cc
- server/spectatord.h
- server/spectatord_test.cc
- server/udp_server.cc
- server/udp_server.h
There are some systems which cannot run IPv6 at all, and the previous default behavior of spectatord meant that the process crashes when attempting to listen on a udp6 socket.
This change adds an optional parameter --ipv4_only, defaulting to false, which will configure the socket listener to use udp4 instead of udp6.
When using the udp6 socket, the server is capable of receiving udp packets from IPv4 on dual-stacked instances with IPv4-mapped IPv6 addresses enabled.
> add --ipv4_only parameter (default = false)

- README.md
- conanfile.py
- server/spectatord.cc
There was no feedback mechanism for poorly formatted protocol messages, because the errors were not logged. This change logs those errors, at INFO level, so that we do not trigger exception alerts.
External publishing now needs a slightly longer connect timeout, in order for connections to succeed. Update the netflix-spectatord-cppconf library to make this happen.
> log parse errors

- bin/spectatord_main.cc
- conanfile.py
* Fixes search paths for certificates on MacOS for non-interactive systems.
* Add a proper version string to the binary.
* Internal downloads no longer require the `-k` option.
> update metatron config library

- spectator/http_client.cc
We see occasional HTTP errors when POSTing data to the backend. These are often transient errors, and there is nothing that an end user can do about them. Since we are ingesting spectatord logs, this results in creating exception alerts, and we do not want this to happen. Thus, we turn down the log levels for HTTP errors to info level, to prevent this scenario.
> reduce logging levels for http errors

- .github/workflows/build.yml
- build.sh
Internally, bumping from gcc-11 to gcc-13 requires an update of libstdc++ from `8.4.0-1ubuntu1~18.04` to `13.1.0-8ubuntu1~18.04`. Our standard images cannot accept this change, so we must downgrade.
> downgrade from gcc-13 to gcc-11

- build.sh
We want to avoid "unsupported GNU_PROPERTY_TYPE" errors when building with gcc-11.
> build all instead of missing for release builds

- .github/workflows/build.yml
- CMakeLists.txt
- build.sh
The libstdc++6 versions can vary much more dramatically than the libc6 versions on a given system, so statically link this library.
This was the cause of issues running on bionic, not gcc-13.
> static link libstdc++ and restore gcc-13

- spectator/compressed_buffer.h
- spectator/compressed_buffer_test.cc
- spectator/smile.cc
Hi, my name is Everett, and I wanted to make some improvements to the **spectatord** project. I firmly believe I can really contribute to this team and project. I recently applied for the L4 role.
I took it upon myself to look at the **spectatord** repo and tried to find an area for improvement. I stumbled upon the `compressed_buffer` implementation, which I assume is called quite frequently, so I made some changes and will describe them below.
The first change I made was function unification. The compressed_buffer had several overloads of the `Append()` function. The internal implementations of the functions were also nearly identical. The only difference being the `parameter types`, `argument count,` and amount of calls to `push_back()`.
```cpp
auto Append(std::string_view s);
auto …
```
> Compressed_Buffer_Improvements

- Dockerfiles/Ubuntu.Dockerfile
- Dockerfiles/Ubuntu.Dockerfile.dockerignore
- README.md
- docs/DOCKERBUILD.md
Hi, Matthew, I hope you enjoyed your holidays :fireworks:. Your positive feedback on my previous pull request was encouraging, so I decided to make a few more :smiley:. This is the first one. This pull request enables you to build the project with `Docker` as the only required dependency and introduces the following benefits:
- Developers can now test their feature branches in an environment nearly identical to the one specified in your `build.yml`.
- The project can easily be built across Linux, Mac, and Windows provided they have `docker`.
- Managers, students, directors, and fellow Netflix employees who might not be technically savvy with resolving local build dependencies (though few) have a reliable way to build the project. 
From the project's root directory, you can now run the …
> Add Docker Support

- spectator/id.h
- spectator/measurement.h
- spectator/tags.h
This is a fix that ensures your project can successfully build with `C++23` should you choose to upgrade. While exploring the project, I noticed that switching to a newer C++ version caused build failures. This pull request addresses those issues, allowing you to safely bump your `CMAKE_CXX_STANDARD` to `23` if desired.
Here is a screenshot of the build errors I was encountering.
You can easily reproduce them in the docker container with the following changes I have in my branch [BuildFailuresC++23](https://github.com/ecbadeaux/spectatord/tree/BuildFailuresC%2B%2B23).
After inspecting the build errors, I was able to see that you were attempting to overload the `stream insertion` operators for the classes `Tag`, `Id`, and `Measurement`. In each of these classes, you were defining the …
> C++23BuildFixes

- .gitignore
- bin/spectatord_main.cc
- conanfile.py
- spectator/http_client_test.cc
- spectator/log_entry.h
- spectator/publisher.h
- spectator/registry.cc
- spectator/registry_test.cc
* The `spectator.measurements` internal status metrics were not being published on 200 OK responses, only when partial errors were observed. This change fixes that, so that we always publish the sent metrics counter on 200 OK.
* The `spectator.measurements` metrics were using the `owner` tag to identify the source of the metrics. Our internal dashboards use the `nf.process` tag for this purpose, so we want to use that instead.
* The `ipc.client.call` metrics were using the `owner` tag to identify the source of the metrics. The `owner` tag is better considered to be a way to identify a source library, when there could be many sources of a metric. It is better to use `nf.process` to identify these metrics.
* The `spectator.registrySize` metrics were using the `owner` tag to identify the …
> fix `spectator.measurements` metrics
